### ISSUE TITLE
[Feature Request] Cropping functionality

### ISSUE THREAD

**Issue by thx4ever** [wwww-wwww/py-aomenc-by-gop#1]
Hi, i have used your program always 24/7 on my server for vp9 video encoding, one function that need this program is cropping video like if the video is 1920x1080 but the aspect ratio are 2.40:1 so we crop 140 from top and 140 from botton and the final video size will be 1920x800

Regards

**Comment by wwww-wwww** [comment]
I hope this is sufficient.
`--extra-filter="clip = clip.std.Crop(top=140, bottom=140)"`

**Comment by thx4ever** [comment]
it works thanks
